dist: trusty

addons:
  postgresql: "9.5"
  apt:
    packages:
      - postgresql-9.5-postgis-2.3
      - postgresql-plpython-9.5

env:
  - PGUSER=postgres
  - DEBUG=*

language: node_js
node_js:
  - "0.10"
  - "6"
