#!/usr/bin/env node

'use strict';

var fs = require('fs');
var debug = require('../lib/util/debug')('cli');

var argv = require('yargs')
    .help('h')
    .alias('h', 'help')
    .usage('Usage: $0 <filename> -o [path]')
    .demand(1)
    .example('$0 examples/def/trade_area_atm_machines.json -o image.png', 'exports trade area analysis workflow')
    .demand('u')
    .alias('u', 'username')
    .argv;

var Analysis = require('../lib/analysis');

var filename = argv._[0];
if (!filename) {
    console.error('Must specify a json file');
    process.exit(1);
}
if (!fs.existsSync(filename)) {
    console.error('File "%s" does not exist', filename);
    process.exit(1);
}
filename = fs.realpathSync(filename);

var username = argv.username;

var analysisDefinition = require(filename);


Analysis.create(username, analysisDefinition, function(err, analysis) {
    if (err) {
        console.error('Error happened: %s', err.message || 'unknown error');
        process.exit(1);
    }

    debug('[INFO] Most likely your query will NOT have the_geom_webmercator.');
    debug('[INFO] You will need to `st_transform(the_geom, 3857) the_geom_webmercator`.');
    console.log('Query for your analysis is: "%s".', analysis.getQuery());
    process.exit(0);
});
